// Turnos jogáveis — fonte da verdade, escrita à mão (não gerada).
//
// Diferente do catálogo de produtos, os turnos carregam intenção pedagógica
// específica e nomeada ("este turno ensina interação medicamentosa"). Gerar o
// cronograma de chegadas/paciência proceduralmente diluiria essa intenção sem
// ganho real nessa escala (8-10 turnos). Todo o rigor de "isso funciona mesmo"
// fica em src/game/shiftValidator.js + scripts/validateShifts.mjs, rodado com
// `npm run validate` sempre que este arquivo muda.
//
// Curva (o que cada turno introduz):
//   01  ler o nome exato na prateleira
//   02  marca x genérico (intercambialidade)
//   03  o cliente descreve o sintoma, não o remédio — e a primeira anamnese
//   04  quem vai tomar não é quem está no balcão + faixa etária
//   05  condições declaradas (gestante, lactante, hipertensão)
//   06  validade do lote
//   07  alergia medicamentosa e reação cruzada de classe
//   08  interação, duplicidade terapêutica e o primeiro sinal de alerta
//   09  controlados, retenção de receita e distrações
//   10  tudo junto, com dois quadros que não são de automedicação
//
// Do turno 3 em diante o pedido por NOME é exceção: a maioria dos clientes
// chega descrevendo o que sente, e cabe ao jogador chegar no princípio ativo e
// na apresentação. Pedido por nome/genérico fica reservado para o que de fato
// se pede assim na vida real — medicamento de uso conhecido, receita na mão,
// controlado — e para exercitar intercambialidade.
//
// Regra de ouro ao escrever um cliente: a informação que decide o atendimento
// NÃO pode estar na fala dele. A fala dá a queixa e, no máximo, uma pista; o
// dado que muda a decisão (idade de quem vai tomar, gravidez, remédio de uso
// contínuo, alergia, há quanto tempo o quadro dura, receita em mãos) tem que
// sair da anamnese — senão a pergunta vira enfeite e o turno volta a ser "leia
// a ficha e compare".
//
// estoque[].id é único dentro de cada turno (não precisa ser global).
// arrivals[].request.type: 'produto' | 'generico' | 'sintoma' | 'receita'.

import { PRODUCTS } from './products.js'

const sec = (n) => n * 1000

function estoqueDeCategorias(categorias, { extras = [], vencidos = [] } = {}) {
  const base = PRODUCTS.filter((p) => categorias.includes(p.categoria)).map((p) => ({
    id: p.id,
    produtoId: p.id,
    // um produto listado em `vencidos` só existe no turno como lote vencido:
    // não há alternativa boa, então o atendimento certo é recusar.
    validadeStatus: vencidos.includes(p.id) ? 'vencido' : 'ok',
  }))
  return [...base, ...extras]
}

// Lote vencido ADICIONAL do mesmo produto — na prateleira ele aparece como
// "Lote A / Lote B" e a validade só é revelada na tela de confirmação.
function loteVencido(produtoId) {
  return { id: `${produtoId}-lote-vencido`, produtoId, validadeStatus: 'vencido' }
}

// `quadro`/`sinalDeAlerta` valem para qualquer tipo de pedido, não só sintoma:
// quem chega pedindo a marca pelo nome também pode estar num quadro que não é
// de balcão (o caso clássico é o descongestionante nasal de uso diário).
function pedidoProduto(produtoId, rotulo, mensagem, { quadro, sinalDeAlerta } = {}) {
  return { type: 'produto', produtoId, rotulo, mensagem, quadro, sinalDeAlerta }
}

// "Tem o genérico?" — só vale o genérico com o MESMO princípio ativo e a MESMA
// dose do medicamento de referência citado. Princípio ativo e dose são copiados
// do catálogo para o pedido não poder divergir dele.
function pedidoGenerico(produtoReferenciaId, mensagem) {
  const referencia = PRODUCTS.find((p) => p.id === produtoReferenciaId)
  if (!referencia) throw new Error(`Referência desconhecida no pedido: ${produtoReferenciaId}`)
  return {
    type: 'generico',
    produtoReferenciaId,
    principioAtivo: referencia.principioAtivo,
    dose: referencia.dose,
    rotulo: referencia.nome,
    mensagem,
  }
}

// `principiosAceitos` é o que resolveria a queixa — inclusive o que um
// atendente apressado pegaria num quadro que na verdade é de encaminhamento.
// `quadro` é o que o cliente conta quando perguntam "como é exatamente?", e
// `sinalDeAlerta`, quando presente, é o achado que tira o caso da automedicação.
// `criterio` é o raciocínio clínico em uma frase: o que ESTE quadro pede, e por
// quê. Aparece quando o jogador escolhe um item que não atende. Sem ele a
// recusa vira "esse remédio não serve", que é confuso justamente quando o item
// escolhido é vizinho de gôndola do certo — antitussígeno em tosse produtiva,
// anti-histamínico em nariz entupido. Escreva um sempre que o erro for
// plausível, ou seja: quase sempre.
function pedidoSintoma(rotulo, mensagem, principiosAceitos, { quadro, sinalDeAlerta, criterio } = {}) {
  return { type: 'sintoma', rotulo, mensagem, principiosAceitos, quadro, sinalDeAlerta, criterio }
}

function pedidoReceita(rotulo, mensagem, itens) {
  return { type: 'receita', rotulo, mensagem, itens }
}

// Quem vai tomar o remédio, quando não é o cliente. A idade, as condições e as
// alergias daqui só aparecem na ficha depois das perguntas correspondentes.
function paciente(descricao, idade, { pronome = 'ela', tags = [], jaToma = [], alergias = [] } = {}) {
  return {
    relacao: 'terceiro',
    descricao,
    idade,
    pronome,
    tags,
    jaTomaPrincipiosAtivos: jaToma,
    alergias,
  }
}

export const SHIFTS = [
  // ------------------------------------------------------------------------
  {
    id: 'turno-01',
    nome: 'Primeiro Plantão',
    dificuldade: 'fácil',
    resumo: 'Pedidos diretos pelo nome. Só ache o item certo na prateleira — ninguém aqui esconde nada.',
    durationMs: sec(105),
    reputationStart: 60,
    reputationTarget: 68,
    maxQueueVisible: 2,
    unlockedCategories: ['analgesicos'],
    ruleFocus: ['wrongProduct'],
    estoque: estoqueDeCategorias(['analgesicos']),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(70),
        nome: 'Marcos',
        idade: 34,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('novalgina-500', 'Novalgina® 500mg', 'Oi, preciso de Novalgina® 500mg.'),
      },
      {
        id: 'c2',
        arrivalMs: sec(26),
        patienceMaxMs: sec(70),
        nome: 'Beatriz',
        idade: 41,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('tylenol-750', 'Tylenol® 750mg', 'Vim buscar Tylenol® 750mg.'),
      },
      {
        id: 'c3',
        arrivalMs: sec(52),
        patienceMaxMs: sec(68),
        nome: 'Carla',
        idade: 27,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'tylenol-500',
          'Tylenol® 500mg',
          'Quero Tylenol®, mas o de 500 — não o de 750.',
        ),
      },
      {
        id: 'c4',
        arrivalMs: sec(78),
        patienceMaxMs: sec(65),
        nome: 'Jorge',
        idade: 39,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('advil-400', 'Advil® 400mg', 'Me vê um Advil® 400.'),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-02',
    nome: 'Marca ou Genérico',
    dificuldade: 'fácil',
    resumo:
      'Cada referência tem um genérico ao lado. Quem pede o genérico quer mesmo princípio ativo e mesma dose — quem pede a marca, quer a marca.',
    durationMs: sec(115),
    reputationStart: 60,
    reputationTarget: 68,
    maxQueueVisible: 2,
    unlockedCategories: ['analgesicos', 'antialergicos', 'gastrointestinal'],
    ruleFocus: ['wrongProduct'],
    estoque: estoqueDeCategorias(['analgesicos', 'antialergicos', 'gastrointestinal']),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(66),
        nome: 'Renato',
        idade: 30,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoGenerico(
          'tylenol-750',
          'O médico escreveu Tylenol® 750, mas eu queria o genérico, que sai mais barato.',
        ),
      },
      {
        id: 'c2',
        arrivalMs: sec(24),
        patienceMaxMs: sec(66),
        nome: 'Sofia',
        idade: 24,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'claritin-10',
          'Claritin® 10mg',
          'Quero o Claritin® 10mg mesmo, o de marca — genérico eu não levo.',
        ),
      },
      {
        id: 'c3',
        arrivalMs: sec(48),
        patienceMaxMs: sec(64),
        nome: 'Diego',
        idade: 45,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('azia', 'Comi demais e estou com uma azia terrível.', ['omeprazol', 'hidroxido_de_aluminio'], { criterio: 'azia é ácido: pede inibidor de bomba de prótons ou antiácido, não antiespasmódico nem antiflatulento' }),
      },
      {
        id: 'c4',
        arrivalMs: sec(72),
        patienceMaxMs: sec(64),
        nome: 'Paula',
        idade: 38,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoGenerico('advil-400', 'Tem o genérico do Advil® 400? É pra uma dor no joelho.'),
      },
      {
        id: 'c5',
        arrivalMs: sec(94),
        patienceMaxMs: sec(62),
        nome: 'Otávio',
        idade: 33,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor de cabeça', 'Tô com uma dor de cabeça desde cedo.', ['dipirona', 'paracetamol', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'dor sem sinal de alerta pede analgésico simples — a escolha entre eles depende das restrições do paciente' }),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-03',
    nome: 'O Que Você Sente',
    dificuldade: 'fácil-médio',
    resumo:
      'A partir daqui quase ninguém diz o nome do remédio — dizem o que sentem. E a ficha do cliente só mostra o que você perguntar.',
    durationMs: sec(130),
    reputationStart: 60,
    reputationTarget: 70,
    maxQueueVisible: 3,
    unlockedCategories: ['analgesicos', 'antialergicos', 'gastrointestinal', 'antibioticos'],
    ruleFocus: ['requiresPrescription', 'controlledWithoutRetention'],
    estoque: estoqueDeCategorias(['analgesicos', 'antialergicos', 'gastrointestinal', 'antibioticos']),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(72),
        nome: 'Júlia',
        idade: 29,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor de cabeça', 'Estou com uma dor de cabeça que não passa.', ['dipirona', 'paracetamol', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'dor sem sinal de alerta pede analgésico simples — a escolha entre eles depende das restrições do paciente' }),
      },
      {
        id: 'c2',
        arrivalMs: sec(23),
        patienceMaxMs: sec(72),
        nome: 'Eduardo',
        idade: 52,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('amoxil-500', 'Amoxil® 500mg', 'O médico passou Amoxil® 500mg pra mim.'),
      },
      {
        id: 'c3',
        arrivalMs: sec(47),
        patienceMaxMs: sec(70),
        nome: 'Larissa',
        idade: 33,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'amoxicilina-gen-500',
          'Amoxicilina 500mg',
          'Me vê uma amoxicilina de 500. É só uma garganta inflamada, já tomei antes.',
        ),
      },
      {
        id: 'c4',
        arrivalMs: sec(71),
        patienceMaxMs: sec(68),
        nome: 'Otávio',
        idade: 41,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Estou espirrando muito e com coceira nos olhos.', [
          'loratadina',
          'cetirizina',
        ], { criterio: 'rinite alérgica pede anti-histamínico; prefira os de 2ª geração (loratadina, cetirizina), que não sedam' }),
      },
      {
        id: 'c5',
        arrivalMs: sec(95),
        patienceMaxMs: sec(66),
        nome: 'Nina',
        idade: 26,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('queimação no estômago', 'Tenho uma queimação no estômago quase todo dia.', [
          'omeprazol',
          'hidroxido_de_aluminio',
        ], { criterio: 'queimação retroesternal recorrente é refluxo ácido: pede inibidor de bomba de prótons ou antiácido' }),
      },
      {
        id: 'c6',
        arrivalMs: sec(117),
        patienceMaxMs: sec(64),
        nome: 'Caio',
        idade: 36,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoGenerico('losec-20', 'Tem o genérico do Losec® 20?'),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-04',
    nome: 'Não É Para Mim',
    dificuldade: 'médio',
    resumo:
      'Quem está no balcão nem sempre é quem vai tomar. Pergunte para quem é — a apresentação tem que servir à idade certa. E aparece aqui a primeira CAUTELA: restrição que não proíbe a venda, mas exige orientar o paciente.',
    durationMs: sec(135),
    reputationStart: 60,
    reputationTarget: 73,
    maxQueueVisible: 4,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'antibioticos',
    ],
    ruleFocus: ['wrongAgeGroup', 'cautionWithoutCounseling'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'antibioticos',
    ]),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(74),
        nome: 'Camila',
        idade: 33,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('meu filho', 5, { pronome: 'ele' }),
        request: pedidoSintoma('febre', 'Meu filho está com febre desde ontem, o que eu dou pra ele?', ['paracetamol', 'dipirona', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'febre pede antitérmico, na apresentação adequada à idade de quem vai tomar' }),
      },
      {
        id: 'c2',
        arrivalMs: sec(23),
        patienceMaxMs: sec(72),
        nome: 'Thiago',
        idade: 38,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('gripe', 'Peguei uma gripe, tô com o nariz entupido e o corpo doendo.', [
          'fenilefrina',
        ], { criterio: 'congestão nasal com dor pede descongestionante associado a analgésico; analgésico puro não desentope' }),
      },
      {
        id: 'c3',
        arrivalMs: sec(47),
        patienceMaxMs: sec(72),
        nome: 'Lívia',
        idade: 30,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('minha mãe', 71),
        request: pedidoSintoma('cólica', 'É pra minha mãe, ela está com muita cólica intestinal.', ['butilescopolamina'], { criterio: 'cólica é espasmo de musculatura lisa: pede antiespasmódico (butilescopolamina)' }),
      },
      {
        id: 'c4',
        arrivalMs: sec(71),
        patienceMaxMs: sec(70),
        nome: 'Patrícia',
        idade: 27,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('meu filho', 8, { pronome: 'ele' }),
        request: pedidoSintoma(
          'gripe',
          'Meu filho está muito gripado, com o nariz entupido e um pouco de febre.',
          ['paracetamol', 'fenilefrina'], { criterio: 'em criança o que se dispensa é o antitérmico na apresentação da idade; antigripal de adulto está fora' }),
      },
      {
        id: 'c5',
        arrivalMs: sec(95),
        patienceMaxMs: sec(68),
        nome: 'André',
        idade: 45,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoGenerico('tylenol-750', 'Tem o genérico do Tylenol® 750?'),
      },
      {
        id: 'c6',
        arrivalMs: sec(117),
        patienceMaxMs: sec(68),
        nome: 'Solange',
        idade: 29,
        humor: 'estressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('minha filha', 5),
        request: pedidoSintoma(
          'diarreia',
          'Minha filha está com diarreia desde ontem, queria alguma coisa pra cortar.',
          ['loperamida', 'sais_de_reidratacao'], { criterio: 'em criança com diarreia aguda o que se dispensa é reidratação oral; antidiarreico está contraindicado na idade dela' }),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-05',
    nome: 'Gestante na Fila',
    dificuldade: 'médio',
    resumo:
      'Gravidez, amamentação e pressão alta mudam o que pode sair do balcão — e ninguém conta isso sem ser perguntado.',
    durationMs: sec(135),
    reputationStart: 60,
    reputationTarget: 75,
    maxQueueVisible: 4,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'dermatologicos',
      'antibioticos',
    ],
    ruleFocus: ['contraindication'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'dermatologicos',
      'antibioticos',
    ]),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(74),
        nome: 'Bruna',
        idade: 29,
        humor: 'neutro',
        tags: ['gravidez'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor nas costas', 'Estou com uma dor nas costas que não passa com nada.', ['dipirona', 'paracetamol', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'dor sem sinal de alerta pede analgésico simples — a escolha entre eles depende das restrições do paciente' }),
      },
      {
        id: 'c2',
        arrivalMs: sec(23),
        patienceMaxMs: sec(72),
        nome: 'Onofre',
        idade: 68,
        humor: 'estressado',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('gripe', 'Tô gripado, com o nariz entupido e febre.', [
          'fenilefrina',
          'paracetamol',
        ], { criterio: 'congestão nasal pede descongestionante; se ele estiver fora de questão, trate o que dá para tratar (a febre)' }),
      },
      {
        id: 'c3',
        arrivalMs: sec(47),
        patienceMaxMs: sec(72),
        nome: 'Talita',
        idade: 31,
        humor: 'neutro',
        tags: ['lactante'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor de cabeça', 'Estou com uma dor de cabeça constante há dois dias.', ['dipirona', 'paracetamol', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'dor sem sinal de alerta pede analgésico simples — a escolha entre eles depende das restrições do paciente' }),
      },
      {
        id: 'c4',
        arrivalMs: sec(71),
        patienceMaxMs: sec(72),
        nome: 'Vitor',
        idade: 40,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('minha esposa', 34, { tags: ['gravidez'] }),
        request: pedidoSintoma('dor muscular', 'Minha esposa torceu o pé. Queria uma pomada boa pra dor.', [
          'ibuprofeno',
          'diclofenaco',
        ], { criterio: 'o cliente quer uso tópico: pede anti-inflamatório em gel ou creme' }),
      },
      {
        id: 'c5',
        arrivalMs: sec(95),
        patienceMaxMs: sec(68),
        nome: 'Cléber',
        idade: 37,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoGenerico('advil-400', 'Tem o genérico do Advil® 400?'),
      },
      {
        id: 'c6',
        arrivalMs: sec(117),
        patienceMaxMs: sec(66),
        nome: 'Rosa',
        idade: 55,
        humor: 'neutro',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Estou com uma coceira que não para.', ['loratadina', 'cetirizina'], { criterio: 'prurido alérgico pede anti-histamínico de 2ª geração (loratadina, cetirizina), que não seda' }),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-06',
    nome: 'Estoque Vencido',
    dificuldade: 'médio-avançado',
    resumo:
      'Alguns lotes estão vencidos e a prateleira não avisa: a validade só aparece na confirmação. Um item vencido com lote bom ao lado não é motivo pra recusar — é motivo pra pegar o outro.',
    durationMs: sec(140),
    reputationStart: 60,
    reputationTarget: 76,
    maxQueueVisible: 4,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'dermatologicos',
      'antibioticos',
    ],
    ruleFocus: ['expiredProduct'],
    estoque: estoqueDeCategorias(
      ['analgesicos', 'antialergicos', 'antigripais', 'gastrointestinal', 'dermatologicos', 'antibioticos'],
      {
        // lotes duplicados: existe um bom e um vencido do mesmo produto
        extras: [loteVencido('novalgina-500'), loteVencido('claritin-10'), loteVencido('bepantol-derma')],
        // sem alternativa: todo paracetamol de adulto do turno está vencido
        vencidos: ['tylenol-500', 'tylenol-750', 'paracetamol-gen-750'],
      },
    ),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(74),
        nome: 'Simone',
        idade: 35,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('novalgina-500', 'Novalgina® 500mg', 'Uma Novalgina® 500, por favor.'),
      },
      {
        id: 'c2',
        arrivalMs: sec(23),
        patienceMaxMs: sec(72),
        nome: 'Bruno',
        idade: 42,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('febre', 'Tô com febre, e só paracetamol funciona comigo.', ['paracetamol'], { criterio: 'o cliente pediu paracetamol especificamente, e não é caso de empurrar outro princípio ativo' }),
      },
      {
        id: 'c3',
        arrivalMs: sec(47),
        patienceMaxMs: sec(72),
        nome: 'Denise',
        idade: 30,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('minha filha', 6),
        request: pedidoSintoma('febre', 'Minha filha está com febre e não quer comer nada.', ['paracetamol', 'dipirona', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'febre pede antitérmico, na apresentação adequada à idade de quem vai tomar' }),
      },
      {
        id: 'c4',
        arrivalMs: sec(71),
        patienceMaxMs: sec(70),
        nome: 'Gustavo',
        idade: 47,
        humor: 'neutro',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor no ombro', 'Machuquei o ombro na academia, tá inflamado.', ['ibuprofeno', 'acido_acetilsalicilico', 'dipirona', 'paracetamol'], { criterio: 'dor com inflamação responde melhor a anti-inflamatório (AINE); analgésico simples alivia a dor, mas não trata a inflamação' }),
      },
      {
        id: 'c5',
        arrivalMs: sec(95),
        patienceMaxMs: sec(68),
        nome: 'Vitória',
        idade: 25,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('queimadura leve', 'Me queimei na panela, tem alguma pomada?', ['dexpantenol'], { criterio: 'queimadura superficial pede cicatrizante/reepitelizante (dexpantenol); antifúngico e antiviral não têm o que tratar aqui' }),
      },
      {
        id: 'c6',
        arrivalMs: sec(119),
        patienceMaxMs: sec(66),
        nome: 'Renan',
        idade: 39,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma(
          'micose',
          'Tá descamando e coçando entre os dedos do pé faz umas duas semanas.',
          ['clotrimazol'], { criterio: 'micose interdigital pede antifúngico tópico em creme (clotrimazol); xampu antifúngico é para couro cabeludo e creme vaginal é para candidíase' }),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-07',
    nome: 'Tenho Alergia',
    dificuldade: 'avançado',
    resumo:
      'Alergia medicamentosa bloqueia a família inteira, não só a caixa. Quem não pode AINE ainda pode paracetamol e dipirona — saber disso é o trabalho.',
    durationMs: sec(140),
    reputationStart: 60,
    reputationTarget: 77,
    maxQueueVisible: 4,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'dermatologicos',
      'antibioticos',
    ],
    ruleFocus: ['allergy'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'dermatologicos',
      'antibioticos',
    ]),
    distractions: [{ id: 'd1', triggerMs: sec(56), tipo: 'telefone', durationMs: sec(14) }],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(76),
        nome: 'Marina',
        idade: 34,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        alergias: ['penicilina'],
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'amoxil-500',
          'Amoxil® 500mg',
          'O médico passou Amoxil® 500mg, tenho a receita aqui.',
        ),
      },
      {
        id: 'c2',
        arrivalMs: sec(24),
        patienceMaxMs: sec(74),
        nome: 'Paulo',
        idade: 45,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        alergias: ['aine'],
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor no joelho', 'Meu joelho tá doendo muito, queria alguma coisa forte pra dor.', ['ibuprofeno', 'acido_acetilsalicilico', 'dipirona', 'paracetamol'], { criterio: 'dor com inflamação responde melhor a anti-inflamatório (AINE); analgésico simples alivia a dor, mas não trata a inflamação' }),
      },
      {
        id: 'c3',
        arrivalMs: sec(48),
        patienceMaxMs: sec(74),
        nome: 'Sueli',
        idade: 52,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        alergias: ['pirazolona'],
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor de cabeça', 'Uma dor de cabeça chata desde ontem.', ['dipirona', 'paracetamol', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'dor sem sinal de alerta pede analgésico simples — a escolha entre eles depende das restrições do paciente' }),
      },
      {
        id: 'c4',
        arrivalMs: sec(72),
        patienceMaxMs: sec(72),
        nome: 'Téo',
        idade: 29,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor na barriga', 'Tô com um incômodo aqui na barriga, queria alguma coisa.', [
          'simeticona',
        ], {
          criterio:
            'empachamento com gás pede antiflatulento (simeticona); antiespasmódico é para cólica e antiácido é para azia',
          quadro:
            'É mais um estufamento — a barriga fica dura e cheia de gás depois que eu como. Faz uns dois dias, e melhora quando eu solto.',
        }),
      },
      {
        id: 'c5',
        arrivalMs: sec(96),
        patienceMaxMs: sec(72),
        nome: 'Dani',
        idade: 31,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('meu filho', 7, { pronome: 'ele', alergias: ['aine'] }),
        request: pedidoSintoma('febre', 'Meu filho está com febre, preciso de alguma coisa pra baixar.', ['paracetamol', 'dipirona', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'febre pede antitérmico, na apresentação adequada à idade de quem vai tomar' }),
      },
      {
        id: 'c6',
        arrivalMs: sec(120),
        patienceMaxMs: sec(68),
        nome: 'Hugo',
        idade: 40,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoGenerico('claritin-10', 'Queria o genérico do Claritin® 10.'),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-08',
    nome: 'Já Estou Tomando',
    dificuldade: 'avançado',
    resumo:
      'Interação e duplicidade: o que o paciente já toma pode brigar com o pedido — ou já estar escondido na fórmula. E um dos casos aqui não é de farmácia.',
    durationMs: sec(145),
    reputationStart: 60,
    reputationTarget: 78,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'dermatologicos',
      'antibioticos',
      'controlados',
    ],
    ruleFocus: ['drugInteraction', 'duplicateTherapy', 'redFlagReferral'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'dermatologicos',
      'antibioticos',
      'controlados',
    ]),
    distractions: [{ id: 'd1', triggerMs: sec(54), tipo: 'telefone', durationMs: sec(14) }],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(76),
        nome: 'Roberta',
        idade: 44,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['diazepam'],
        request: pedidoSintoma('alergia', 'Estou com uma alergia terrível, o que você me indica?', [
          'loratadina',
          'cetirizina',
          'dexclorfeniramina',
        ], { criterio: 'sintoma alérgico pede anti-histamínico — os de 2ª geração (loratadina, cetirizina) não sedam' }),
      },
      {
        id: 'c2',
        arrivalMs: sec(24),
        patienceMaxMs: sec(74),
        nome: 'Cláudio',
        idade: 51,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['paracetamol'],
        request: pedidoSintoma('gripe', 'Peguei um resfriado, queria um antigripal desses.', [
          'fenilefrina',
          'paracetamol',
        ], { criterio: 'o cliente quer um antigripal — associação de descongestionante com analgésico' }),
      },
      {
        id: 'c3',
        arrivalMs: sec(48),
        patienceMaxMs: sec(74),
        nome: 'Fernanda',
        idade: 36,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['dipirona'],
        request: pedidoSintoma('dor de cabeça', 'Uma dor de cabeça daquelas. O que eu levo?', ['dipirona', 'paracetamol', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'dor sem sinal de alerta pede analgésico simples — a escolha entre eles depende das restrições do paciente' }),
      },
      {
        id: 'c4',
        arrivalMs: sec(72),
        patienceMaxMs: sec(74),
        nome: 'Ivo',
        idade: 47,
        humor: 'estressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma(
          'dor de cabeça',
          'Queria alguma coisa forte pra dor de cabeça, o que vocês têm de melhor?',
          ['dipirona', 'paracetamol', 'ibuprofeno'],
          {
            quadro:
              'Já faz umas três semanas, e tem piorado. De manhã eu acordo enjoado e às vezes vomito antes de tomar café.',
            sinalDeAlerta:
              'Cefaleia com três semanas de evolução, progressiva, com vômito matinal',
          },
        ),
      },
      {
        id: 'c5',
        arrivalMs: sec(97),
        patienceMaxMs: sec(72),
        nome: 'Priscila',
        idade: 33,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: ['dexclorfeniramina'],
        request: pedidoProduto('valium-5', 'Valium® 5mg', 'Trouxe a receita do Valium® 5mg.'),
      },
      {
        id: 'c6',
        arrivalMs: sec(121),
        patienceMaxMs: sec(68),
        nome: 'Nilton',
        idade: 38,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoGenerico('losec-20', 'Tem o genérico do Losec® 20?'),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-09',
    nome: 'Retenção Obrigatória',
    dificuldade: 'expert',
    resumo:
      'Tarja preta, tarja vermelha e antimicrobiano: além da receita, é preciso retê-la. E o telefone não para de tocar.',
    durationMs: sec(150),
    reputationStart: 60,
    reputationTarget: 80,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'dermatologicos',
      'antibioticos',
      'controlados',
    ],
    ruleFocus: ['controlledWithoutRetention', 'requiresPrescription'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'dermatologicos',
      'antibioticos',
      'controlados',
    ]),
    distractions: [
      { id: 'd1', triggerMs: sec(40), tipo: 'telefone', durationMs: sec(13) },
      {
        id: 'd2',
        triggerMs: sec(100),
        tipo: 'troco',
        durationMs: sec(15),
        options: [
          { id: 'a', label: 'R$ 12,50' },
          { id: 'b', label: 'R$ 13,50' },
          { id: 'c', label: 'R$ 17,50' },
        ],
        correctChoiceId: 'b',
        enunciado: 'A cliente pagou R$ 50,00 numa compra de R$ 36,50. Quanto é o troco?',
      },
    ],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(78),
        nome: 'Marcelo',
        idade: 47,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('tylex-30', 'Tylex® 30mg', 'Vim buscar o Tylex® 30mg que o médico passou.'),
      },
      {
        id: 'c2',
        arrivalMs: sec(24),
        patienceMaxMs: sec(76),
        nome: 'Elaine',
        idade: 34,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('meu filho', 9, { pronome: 'ele' }),
        request: pedidoProduto('tylex-30', 'Tylex® 30mg', 'É pro meu filho, o pediatra passou Tylex® 30mg.'),
      },
      {
        id: 'c3',
        arrivalMs: sec(48),
        patienceMaxMs: sec(76),
        nome: 'Ricardo',
        idade: 55,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('valium-5', 'Valium® 5mg', 'Valium® 5mg — a receita está aqui.'),
      },
      {
        id: 'c4',
        arrivalMs: sec(73),
        patienceMaxMs: sec(74),
        nome: 'Tânia',
        idade: 39,
        humor: 'neutro',
        tags: ['gravidez'],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('valium-5', 'Valium® 5mg', 'Preciso do Valium® 5mg, tenho a receita.'),
      },
      {
        id: 'c5',
        arrivalMs: sec(98),
        patienceMaxMs: sec(72),
        nome: 'Felipe',
        idade: 28,
        humor: 'apressado',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoGenerico('amoxil-500', 'Tem o genérico do Amoxil® 500? A receita está comigo.'),
      },
      {
        id: 'c6',
        arrivalMs: sec(123),
        patienceMaxMs: sec(72),
        nome: 'Aline',
        idade: 31,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('meu filho', 7, { pronome: 'ele' }),
        request: pedidoSintoma(
          'infecção de garganta',
          'O médico passou antibiótico pro meu filho, está tudo na receita.',
          ['amoxicilina'], { criterio: 'o antimicrobiano é o da receita, na apresentação adequada à idade de quem vai tomar' }),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-10',
    nome: 'Fechamento Perfeito',
    dificuldade: 'expert/mestre',
    resumo:
      'Turno de prova: todas as regras em jogo, fila cheia, lote vencido no meio, receita com dois itens, três distrações — e dois quadros que não são pra resolver no balcão.',
    durationMs: sec(160),
    reputationStart: 60,
    reputationTarget: 84,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'dermatologicos',
      'antibioticos',
      'controlados',
    ],
    ruleFocus: [
      'requiresPrescription',
      'controlledWithoutRetention',
      'contraindication',
      'drugInteraction',
      'duplicateTherapy',
      'allergy',
      'wrongAgeGroup',
      'expiredProduct',
      'redFlagReferral',
      'wrongProduct',
    ],
    estoque: estoqueDeCategorias(
      [
        'analgesicos',
        'antialergicos',
        'antigripais',
        'gastrointestinal',
        'dermatologicos',
        'antibioticos',
        'controlados',
      ],
      { extras: [loteVencido('novalgina-500'), loteVencido('amoxicilina-gen-500'), loteVencido('losec-20')] },
    ),
    distractions: [
      { id: 'd1', triggerMs: sec(36), tipo: 'telefone', durationMs: sec(12) },
      {
        id: 'd2',
        triggerMs: sec(88),
        tipo: 'troco',
        durationMs: sec(13),
        options: [
          { id: 'a', label: 'R$ 8,20' },
          { id: 'b', label: 'R$ 11,80' },
          { id: 'c', label: 'R$ 18,20' },
        ],
        correctChoiceId: 'b',
        enunciado: 'O cliente pagou R$ 30,00 numa compra de R$ 18,20. Quanto é o troco?',
      },
      { id: 'd3', triggerMs: sec(132), tipo: 'telefone', durationMs: sec(11) },
    ],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(82),
        nome: 'Sandra',
        idade: 36,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: ['omeprazol'],
        request: pedidoReceita(
          'receita com 2 itens',
          'O médico passou dois remédios aqui na receita.',
          [
            { principioAtivo: 'amoxicilina', rotulo: 'Amoxicilina 500mg' },
            { principioAtivo: 'dipirona', rotulo: 'Dipirona 500mg' },
          ],
        ),
      },
      {
        id: 'c2',
        arrivalMs: sec(24),
        patienceMaxMs: sec(78),
        nome: 'Henrique',
        idade: 63,
        humor: 'estressado',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('gripe forte', 'Peguei uma gripe braba, tô acabado.', [
          'fenilefrina',
          'paracetamol',
        ], { criterio: 'congestão com dor pede descongestionante associado a analgésico; se o descongestionante estiver fora, resta tratar a febre e a dor' }),
      },
      {
        id: 'c3',
        arrivalMs: sec(47),
        patienceMaxMs: sec(78),
        nome: 'Gabriela',
        idade: 28,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('minha filha', 4),
        request: pedidoSintoma('febre', 'Minha filha está queimando de febre.', ['paracetamol', 'dipirona', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'febre pede antitérmico, na apresentação adequada à idade de quem vai tomar' }),
      },
      {
        id: 'c4',
        arrivalMs: sec(70),
        patienceMaxMs: sec(76),
        nome: 'Sérgio',
        idade: 58,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma(
          'dor no peito',
          'Acho que é gases. Dá uma dor aqui no meio do peito, queria alguma coisa pra soltar.',
          ['simeticona', 'hidroxido_de_aluminio'],
          {
            quadro:
              'Aperta bem no meio do peito quando eu subo a escada, e sobe pro braço esquerdo. Quando eu paro e descanso, passa.',
            sinalDeAlerta:
              'Dor torácica em aperto, desencadeada por esforço e com irradiação para o braço esquerdo',
          },
        ),
      },
      {
        id: 'c5',
        arrivalMs: sec(93),
        patienceMaxMs: sec(74),
        nome: 'Márcio',
        idade: 44,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['paracetamol'],
        request: pedidoSintoma('gripe', 'Tô gripado, queria um antigripal desses de tomar de dia.', [
          'fenilefrina',
        ], { criterio: 'o cliente quer um antigripal de uso diurno — associação de descongestionante com analgésico, sem anti-histamínico sedativo' }),
      },
      {
        id: 'c6',
        arrivalMs: sec(114),
        patienceMaxMs: sec(74),
        nome: 'Adriana',
        idade: 30,
        humor: 'neutro',
        tags: ['gravidez'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('azia', 'Estou com muita azia, principalmente à noite.', [
          'omeprazol',
          'hidroxido_de_aluminio',
        ], { criterio: 'azia é ácido: pede inibidor de bomba de prótons ou antiácido' }),
      },
      {
        id: 'c7',
        arrivalMs: sec(135),
        patienceMaxMs: sec(72),
        nome: 'Leandro',
        idade: 50,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('valium-5', 'Valium® 5mg', 'Valium® 5mg, com receita.'),
      },
      {
        id: 'c8',
        arrivalMs: sec(152),
        patienceMaxMs: sec(70),
        nome: 'Cristiane',
        idade: 35,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('minha mãe', 70),
        request: pedidoSintoma(
          'diarreia',
          'É pra minha mãe. Ela tá com diarreia, queria alguma coisa pra cortar.',
          ['loperamida', 'sais_de_reidratacao'],
          {
            quadro: 'Faz três dias, e tem sangue nas fezes. Ela tá com febre alta junto, uns 39 graus.',
            sinalDeAlerta: 'Diarreia com sangue e febre alta há três dias',
          },
        ),
      },
    ],
  },
  // ------------------------------------------------------------------------
  {
    id: 'turno-11',
    nome: 'Tosse de Quem?',
    dificuldade: 'expert',
    resumo:
      'Tosse seca pede antitussígeno; tosse com catarro pede mucolítico — e antitussígeno em tosse produtiva segura a secreção. "Um xarope pra tosse" não é um pedido: é meia informação.',
    durationMs: sec(150),
    reputationStart: 60,
    reputationTarget: 80,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'respiratorios',
      'dermatologicos',
      'antibioticos',
    ],
    ruleFocus: ['wrongProduct', 'wrongAgeGroup', 'redFlagReferral'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'respiratorios',
      'dermatologicos',
      'antibioticos',
    ]),
    distractions: [{ id: 'd1', triggerMs: sec(46), tipo: 'telefone', durationMs: sec(12) }],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(76),
        nome: 'Wagner',
        idade: 41,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma(
          'tosse',
          'Queria um xarope pra tosse, não durmo direito faz uns dias.',
          ['dropropizina'],
          { criterio: 'tosse seca e irritativa pede antitussígeno (dropropizina); mucolítico não tem secreção para fluidificar e não alivia nada', quadro: 'É uma tosse seca, irritativa. Não sai nada, só arranha a garganta. Começou faz três dias.' },
        ),
      },
      {
        id: 'c2',
        arrivalMs: sec(22),
        patienceMaxMs: sec(74),
        nome: 'Eliane',
        idade: 37,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('tosse', 'Me vê um xarope pra tosse, por favor.', ['acetilcisteina', 'ambroxol'], {
          criterio:
            'tosse produtiva pede mucolítico ou expectorante (acetilcisteína, ambroxol); antitussígeno segura a tosse e retém a secreção no pulmão',
          quadro: 'Tá saindo bastante catarro, tosse carregada, principalmente de manhã. Faz uns quatro dias.',
        }),
      },
      {
        id: 'c3',
        arrivalMs: sec(45),
        patienceMaxMs: sec(76),
        nome: 'Juliana',
        idade: 32,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('meu filho', 6, { pronome: 'ele' }),
        request: pedidoSintoma('tosse', 'Meu filho não para de tossir à noite.', ['dropropizina'], {
          criterio:
            'tosse seca e irritativa pede antitussígeno (dropropizina), na apresentação da idade dele',
          quadro: 'É seca, ele tosse a noite inteira e não sai nada. Faz duas noites.',
        }),
      },
      {
        id: 'c4',
        arrivalMs: sec(68),
        patienceMaxMs: sec(74),
        nome: 'Norberto',
        idade: 59,
        humor: 'neutro',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('nariz entupido', 'Tô com o nariz completamente entupido.', [
          'nafazolina',
          'cloreto_de_sodio',
        ], { criterio: 'obstrução nasal é congestão vascular, não histamina — anti-histamínico não desentope. Quem descongestiona é vasoconstritor tópico ou lavagem com solução salina' }),
      },
      {
        id: 'c5',
        arrivalMs: sec(91),
        patienceMaxMs: sec(74),
        nome: 'Rafaela',
        idade: 26,
        humor: 'estressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'sorine-adulto',
          'Sorine® Adulto Solução Nasal',
          'Me vê um Sorine®, o meu acabou hoje de manhã.',
          {
            quadro:
              'Uso todo dia faz umas três semanas. Se eu não pingo, entope tudo de novo em uma hora e eu não consigo respirar.',
            sinalDeAlerta:
              'Uso diário de descongestionante nasal há três semanas, com congestão de rebote ao suspender (rinite medicamentosa)',
          },
        ),
      },
      {
        id: 'c6',
        arrivalMs: sec(113),
        patienceMaxMs: sec(72),
        nome: 'Otacílio',
        idade: 44,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('minha filha', 9),
        request: pedidoSintoma('tosse', 'Minha filha está com uma tosse feia.', ['ambroxol'], {
          criterio:
            'tosse com catarro pede expectorante (ambroxol); antitussígeno em tosse produtiva retém a secreção',
          quadro: 'É com catarro, ela escarra bastante. Faz uns três dias.',
        }),
      },
      {
        id: 'c7',
        arrivalMs: sec(133),
        patienceMaxMs: sec(70),
        nome: 'Bia',
        idade: 30,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoGenerico('claritin-10', 'Tem o genérico do Claritin® 10?'),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-12',
    nome: 'Uso Contínuo',
    dificuldade: 'expert',
    resumo:
      'Pacientes polimedicados, e três graus de restrição no mesmo turno: anti-inflamatório ORAL sobre anticoagulante é muro; o mesmo AINE em GEL é cautela, porque a absorção é outra; e sobre anti-hipertensivo é cautela também. A pergunta que salva é "está tomando algum outro medicamento?".',
    durationMs: sec(155),
    reputationStart: 60,
    reputationTarget: 82,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'respiratorios',
      'dermatologicos',
      'antibioticos',
      'cronicos',
    ],
    ruleFocus: ['drugInteraction', 'cautionWithoutCounseling', 'contraindication'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'respiratorios',
      'dermatologicos',
      'antibioticos',
      'cronicos',
    ]),
    distractions: [{ id: 'd1', triggerMs: sec(52), tipo: 'telefone', durationMs: sec(12) }],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(78),
        nome: 'Aparecida',
        idade: 61,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['varfarina'],
        request: pedidoSintoma('dor de cabeça', 'Tô com uma dor de cabeça que não passa.', ['dipirona', 'paracetamol', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'dor sem sinal de alerta pede analgésico simples — a escolha entre eles depende das restrições do paciente' }),
      },
      {
        id: 'c2',
        arrivalMs: sec(22),
        patienceMaxMs: sec(76),
        nome: 'Sebastião',
        idade: 57,
        humor: 'neutro',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['losartana'],
        request: pedidoSintoma('dor no joelho', 'Meu joelho tá inflamado, queria alguma coisa forte.', ['ibuprofeno', 'acido_acetilsalicilico', 'dipirona', 'paracetamol'], { criterio: 'dor com inflamação responde melhor a anti-inflamatório (AINE); analgésico simples alivia a dor, mas não trata a inflamação' }),
      },
      {
        id: 'c3',
        arrivalMs: sec(45),
        patienceMaxMs: sec(76),
        nome: 'Neuza',
        idade: 66,
        humor: 'estressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['varfarina'],
        request: pedidoProduto(
          'aspirina-500',
          'Aspirina® 500mg',
          'Me vê uma Aspirina®. Eu sempre tomo quando dói a cabeça, pode deixar.',
        ),
      },
      {
        id: 'c4',
        arrivalMs: sec(68),
        patienceMaxMs: sec(74),
        nome: 'Reginaldo',
        idade: 54,
        humor: 'neutro',
        tags: ['hipertensao'],
        hasReceita: true,
        jaTomaPrincipiosAtivos: ['losartana'],
        request: pedidoProduto('aradois-50', 'Aradois® 50mg', 'Vim buscar meu remédio de pressão, tenho a receita.'),
      },
      {
        id: 'c5',
        arrivalMs: sec(91),
        patienceMaxMs: sec(76),
        nome: 'Fabiana',
        idade: 35,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('minha mãe', 72, { jaToma: ['varfarina'] }),
        request: pedidoSintoma('dor nas costas', 'É pra minha mãe, ela está com dor nas costas.', ['dipirona', 'paracetamol', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'dor sem sinal de alerta pede analgésico simples — a escolha entre eles depende das restrições do paciente' }),
      },
      {
        id: 'c6',
        arrivalMs: sec(114),
        patienceMaxMs: sec(74),
        nome: 'Válter',
        idade: 49,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['varfarina'],
        // pomada "não é remédio de verdade" — mas diclofenaco tópico entra na
        // circulação e some com o anticoagulante do mesmo jeito.
        request: pedidoProduto(
          'cataflam-emulgel',
          'CataflamPro® Emulgel',
          'Me vê aquele gel pra dor no ombro. É só pomada, nem é remédio de tomar.',
        ),
      },
      {
        id: 'c7',
        arrivalMs: sec(136),
        patienceMaxMs: sec(72),
        nome: 'Solange',
        idade: 44,
        humor: 'neutro',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['losartana'],
        // par deliberado com o Válter (c6): MESMO produto, outro medicamento de
        // uso contínuo, outra conduta. Com varfarina é muro; com losartana é
        // cautela — dispensa, mas orientando. É o contraste que ensina que
        // "interage" não quer dizer "nunca".
        request: pedidoProduto(
          'cataflam-emulgel',
          'CataflamPro® Emulgel',
          'Queria aquele gel pra dor nas costas, o CataflamPro®.',
        ),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-13',
    nome: 'Só Um Minutinho',
    dificuldade: 'mestre',
    resumo:
      'Fila cheia, paciência curta e o telefone tocando sem parar. Todo o conteúdo já visto, mas agora sem tempo pra perguntar tudo a todo mundo: escolha o que vale a pena perguntar.',
    durationMs: sec(160),
    reputationStart: 60,
    reputationTarget: 84,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'respiratorios',
      'dermatologicos',
      'antibioticos',
      'cronicos',
      'controlados',
    ],
    ruleFocus: ['drugInteraction', 'wrongAgeGroup', 'contraindication', 'expiredProduct'],
    estoque: estoqueDeCategorias(
      [
        'analgesicos',
        'antialergicos',
        'antigripais',
        'gastrointestinal',
        'respiratorios',
        'dermatologicos',
        'antibioticos',
        'cronicos',
        'controlados',
      ],
      { extras: [loteVencido('tylenol-500'), loteVencido('luftal-40')] },
    ),
    distractions: [
      { id: 'd1', triggerMs: sec(26), tipo: 'telefone', durationMs: sec(11) },
      {
        id: 'd2',
        triggerMs: sec(66),
        tipo: 'troco',
        durationMs: sec(12),
        options: [
          { id: 'a', label: 'R$ 6,40' },
          { id: 'b', label: 'R$ 13,60' },
          { id: 'c', label: 'R$ 16,40' },
        ],
        correctChoiceId: 'b',
        enunciado: 'A cliente pagou R$ 50,00 numa compra de R$ 36,40. Quanto é o troco?',
      },
      { id: 'd3', triggerMs: sec(106), tipo: 'telefone', durationMs: sec(11) },
      {
        id: 'd4',
        triggerMs: sec(138),
        tipo: 'troco',
        durationMs: sec(12),
        options: [
          { id: 'a', label: 'R$ 4,75' },
          { id: 'b', label: 'R$ 15,25' },
          { id: 'c', label: 'R$ 5,25' },
        ],
        correctChoiceId: 'c',
        enunciado: 'O cliente pagou R$ 20,00 numa compra de R$ 14,75. Quanto é o troco?',
      },
    ],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(74),
        nome: 'Milena',
        idade: 33,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('meu filho', 3, { pronome: 'ele' }),
        request: pedidoSintoma('febre', 'Meu filho tá com febre, me vê alguma coisa rápido.', ['paracetamol', 'dipirona', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'febre pede antitérmico, na apresentação adequada à idade de quem vai tomar' }),
      },
      {
        id: 'c2',
        arrivalMs: sec(20),
        patienceMaxMs: sec(72),
        nome: 'Edson',
        idade: 62,
        humor: 'estressado',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['losartana'],
        request: pedidoSintoma('gripe', 'Peguei uma gripe, tô com o nariz fechado e o corpo mole.', [
          'fenilefrina',
          'paracetamol',
        ], { criterio: 'congestão pede descongestionante; quando ele está fora de questão, trate o que dá para tratar — a dor e a febre' }),
      },
      {
        id: 'c3',
        arrivalMs: sec(41),
        patienceMaxMs: sec(72),
        nome: 'Ariane',
        idade: 28,
        humor: 'neutro',
        tags: ['gravidez'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('tosse', 'Tô com uma tosse com catarro que não passa.', [
          'acetilcisteina',
          'ambroxol',
        ], { criterio: 'tosse produtiva pede mucolítico ou expectorante (acetilcisteína, ambroxol); antitussígeno retém a secreção' }),
      },
      {
        id: 'c4',
        arrivalMs: sec(62),
        patienceMaxMs: sec(72),
        nome: 'Jonas',
        idade: 45,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('tylenol-500', 'Tylenol® 500mg', 'Um Tylenol® 500, por favor.'),
      },
      {
        id: 'c5',
        arrivalMs: sec(83),
        patienceMaxMs: sec(72),
        nome: 'Heloísa',
        idade: 39,
        humor: 'apressado',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoGenerico('amoxil-500', 'Tem o genérico do Amoxil® 500? A receita tá aqui.'),
      },
      {
        id: 'c6',
        arrivalMs: sec(104),
        patienceMaxMs: sec(72),
        nome: 'Ubirajara',
        idade: 70,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Tô com uma coceira no corpo todo.', [
          'loratadina',
          'cetirizina',
          'dexclorfeniramina',
        ], { criterio: 'sintoma alérgico pede anti-histamínico — os de 2ª geração (loratadina, cetirizina) não sedam' }),
      },
      {
        id: 'c7',
        arrivalMs: sec(125),
        patienceMaxMs: sec(70),
        nome: 'Débora',
        idade: 31,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['varfarina'],
        request: pedidoSintoma('cólica', 'Tô com muita cólica menstrual.', ['ibuprofeno', 'acido_acetilsalicilico', 'dipirona', 'paracetamol'], { criterio: 'cólica menstrual responde melhor a anti-inflamatório; analgésico simples alivia, mas não age sobre a inflamação' }),
      },
      {
        id: 'c8',
        arrivalMs: sec(145),
        patienceMaxMs: sec(70),
        nome: 'Ismael',
        idade: 36,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('gases', 'Tô estufado, muito gás depois de comer.', ['simeticona'], { criterio: 'empachamento com gás pede antiflatulento (simeticona), não antiácido nem antiespasmódico' }),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-14',
    nome: 'Não Insista',
    dificuldade: 'mestre',
    resumo:
      'Turno de dizer não. Vários clientes chegam pedindo exatamente o que não podem levar, e com pressa. Recusar bem é atendimento — recusar o cliente errado, não.',
    durationMs: sec(160),
    reputationStart: 62,
    reputationTarget: 84,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'respiratorios',
      'dermatologicos',
      'antibioticos',
      'cronicos',
      'controlados',
    ],
    ruleFocus: ['redFlagReferral', 'requiresPrescription', 'allergy', 'duplicateTherapy'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'respiratorios',
      'dermatologicos',
      'antibioticos',
      'cronicos',
      'controlados',
    ]),
    distractions: [
      { id: 'd1', triggerMs: sec(34), tipo: 'telefone', durationMs: sec(11) },
      { id: 'd2', triggerMs: sec(112), tipo: 'telefone', durationMs: sec(11) },
    ],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(76),
        nome: 'Gilmar',
        idade: 48,
        humor: 'estressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'amoxil-500',
          'Amoxil® 500mg',
          'Me vê um Amoxil® 500. Eu sei o que eu tenho, já tomei isso outras vezes.',
        ),
      },
      {
        id: 'c2',
        arrivalMs: sec(21),
        patienceMaxMs: sec(74),
        nome: 'Lucimara',
        idade: 40,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        alergias: ['aine'],
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'advil-400',
          'Advil® 400mg',
          'Um Advil® 400. Pode ser esse mesmo, é o que sempre funciona comigo.',
        ),
      },
      {
        id: 'c3',
        arrivalMs: sec(43),
        patienceMaxMs: sec(76),
        nome: 'Jefferson',
        idade: 52,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma(
          'dor de estômago',
          'Queria alguma coisa forte pra dor de estômago, tá me matando.',
          ['omeprazol', 'hidroxido_de_aluminio'],
          {
            quadro:
              'Faz umas duas semanas, e de uns dias pra cá o cocô tá preto, tipo borra de café. Tô meio fraco também.',
            sinalDeAlerta: 'Dor epigástrica de duas semanas com fezes escuras (melena) e fraqueza',
          },
        ),
      },
      {
        id: 'c4',
        arrivalMs: sec(66),
        patienceMaxMs: sec(74),
        nome: 'Rosana',
        idade: 34,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['paracetamol'],
        request: pedidoProduto(
          'naldecon-dia',
          'Naldecon® Dia',
          'Me vê um Naldecon® Dia, é o que corta minha gripe.',
        ),
      },
      {
        id: 'c5',
        arrivalMs: sec(89),
        patienceMaxMs: sec(74),
        nome: 'Tarcísio',
        idade: 58,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor de cabeça', 'Queria um remédio pra enxaqueca.', ['dipirona', 'paracetamol', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'dor sem sinal de alerta pede analgésico simples — a escolha entre eles depende das restrições do paciente' }),
      },
      {
        id: 'c6',
        arrivalMs: sec(111),
        patienceMaxMs: sec(74),
        nome: 'Vânia',
        idade: 29,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('meu sobrinho', 5, { pronome: 'ele' }),
        request: pedidoSintoma(
          'diarreia',
          'É pro meu sobrinho, queria alguma coisa pra cortar a diarreia dele.',
          ['loperamida', 'sais_de_reidratacao'],
          {
            quadro: 'Faz dois dias, e hoje começou a ter sangue. Ele tá com febre alta também, quase 39.',
            sinalDeAlerta: 'Diarreia com sangue e febre alta em criança de 5 anos',
          },
        ),
      },
      {
        id: 'c7',
        arrivalMs: sec(133),
        patienceMaxMs: sec(72),
        nome: 'Douglas',
        idade: 37,
        humor: 'estressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'valium-5',
          'Valium® 5mg',
          'Preciso de um Valium® 5, não durmo faz uma semana. Depois eu trago a receita.',
        ),
      },
      {
        id: 'c8',
        arrivalMs: sec(150),
        patienceMaxMs: sec(70),
        nome: 'Regina',
        idade: 45,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('queimadura leve', 'Me queimei no forno, tem pomada?', ['dexpantenol'], { criterio: 'queimadura superficial pede cicatrizante/reepitelizante (dexpantenol)' }),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-15',
    nome: 'Plantão da Madrugada',
    dificuldade: 'mestre',
    resumo:
      'A prova final. Nove clientes, todas as categorias abertas, lotes vencidos, receita com dois itens, quatro distrações e três quadros que não são de balcão. Nada de novo — tudo ao mesmo tempo.',
    durationMs: sec(175),
    reputationStart: 62,
    reputationTarget: 86,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'antigripais',
      'gastrointestinal',
      'respiratorios',
      'dermatologicos',
      'antibioticos',
      'cronicos',
      'controlados',
    ],
    ruleFocus: [
      'requiresPrescription',
      'controlledWithoutRetention',
      'contraindication',
      'drugInteraction',
      'duplicateTherapy',
      'allergy',
      'wrongAgeGroup',
      'expiredProduct',
      'redFlagReferral',
      'wrongProduct',
    ],
    estoque: estoqueDeCategorias(
      [
        'analgesicos',
        'antialergicos',
        'antigripais',
        'gastrointestinal',
        'respiratorios',
        'dermatologicos',
        'antibioticos',
        'cronicos',
        'controlados',
      ],
      {
        extras: [
          loteVencido('novalgina-500'),
          loteVencido('claritin-10'),
          loteVencido('mucosolvan-adulto'),
        ],
      },
    ),
    distractions: [
      { id: 'd1', triggerMs: sec(28), tipo: 'telefone', durationMs: sec(11) },
      {
        id: 'd2',
        triggerMs: sec(72),
        tipo: 'troco',
        durationMs: sec(12),
        options: [
          { id: 'a', label: 'R$ 2,70' },
          { id: 'b', label: 'R$ 7,30' },
          { id: 'c', label: 'R$ 12,70' },
        ],
        correctChoiceId: 'b',
        enunciado: 'A cliente pagou R$ 100,00 numa compra de R$ 92,70. Quanto é o troco?',
      },
      { id: 'd3', triggerMs: sec(118), tipo: 'telefone', durationMs: sec(10) },
      {
        id: 'd4',
        triggerMs: sec(152),
        tipo: 'troco',
        durationMs: sec(11),
        options: [
          { id: 'a', label: 'R$ 9,15' },
          { id: 'b', label: 'R$ 10,85' },
          { id: 'c', label: 'R$ 19,15' },
        ],
        correctChoiceId: 'b',
        enunciado: 'O cliente pagou R$ 30,00 numa compra de R$ 19,15. Quanto é o troco?',
      },
    ],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(84),
        nome: 'Isaura',
        idade: 67,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: ['varfarina'],
        request: pedidoReceita('receita com 2 itens', 'O médico passou dois remédios aqui.', [
          { principioAtivo: 'amoxicilina', rotulo: 'Amoxicilina 500mg' },
          { principioAtivo: 'paracetamol', rotulo: 'Paracetamol 750mg' },
        ]),
      },
      {
        id: 'c2',
        arrivalMs: sec(21),
        patienceMaxMs: sec(78),
        nome: 'Wellington',
        idade: 41,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('tosse', 'Tô com tosse, me vê um xarope.', ['acetilcisteina', 'ambroxol'], {
          criterio:
            'tosse produtiva pede mucolítico ou expectorante (acetilcisteína, ambroxol), não antitussígeno',
          quadro: 'É cheia de catarro, tosse pesada. Faz uns cinco dias.',
        }),
      },
      {
        id: 'c3',
        arrivalMs: sec(42),
        patienceMaxMs: sec(78),
        nome: 'Clarice',
        idade: 30,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('minha filha', 2),
        request: pedidoSintoma('febre', 'Minha filha tá com febre alta desde a tarde.', ['paracetamol', 'dipirona', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'febre pede antitérmico, na apresentação adequada à idade de quem vai tomar' }),
      },
      {
        id: 'c4',
        arrivalMs: sec(63),
        patienceMaxMs: sec(78),
        nome: 'Amadeu',
        idade: 64,
        humor: 'estressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma(
          'dor no peito',
          'Deve ser gastura. Dá um aperto aqui no peito, queria algo pra isso.',
          ['simeticona', 'hidroxido_de_aluminio'],
          {
            quadro:
              'Aperta quando eu ando ligeiro ou subo escada, e sobe pro braço esquerdo. Sento um pouco e alivia. Tá acontecendo faz uma semana.',
            sinalDeAlerta:
              'Dor torácica em aperto desencadeada por esforço, com irradiação para o braço esquerdo e alívio ao repouso',
          },
        ),
      },
      {
        id: 'c5',
        arrivalMs: sec(85),
        patienceMaxMs: sec(76),
        nome: 'Nayara',
        idade: 27,
        humor: 'neutro',
        tags: ['gravidez'],
        hasReceita: false,
        alergias: ['pirazolona'],
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor de cabeça', 'Tô com dor de cabeça desde ontem.', ['dipirona', 'paracetamol', 'ibuprofeno', 'acido_acetilsalicilico'], { criterio: 'dor sem sinal de alerta pede analgésico simples — a escolha entre eles depende das restrições do paciente' }),
      },
      {
        id: 'c6',
        arrivalMs: sec(107),
        patienceMaxMs: sec(76),
        nome: 'Jacira',
        idade: 71,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Tô com uma coceira que não me deixa dormir.', [
          'loratadina',
          'cetirizina',
          'dexclorfeniramina',
        ], { criterio: 'sintoma alérgico pede anti-histamínico — os de 2ª geração (loratadina, cetirizina) não sedam' }),
      },
      {
        id: 'c7',
        arrivalMs: sec(128),
        patienceMaxMs: sec(74),
        nome: 'Eduardo',
        idade: 46,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: ['paracetamol'],
        request: pedidoProduto('tylex-30', 'Tylex® 30mg', 'Trouxe a receita do Tylex® 30.'),
      },
      {
        id: 'c8',
        arrivalMs: sec(149),
        patienceMaxMs: sec(74),
        nome: 'Sirlene',
        idade: 38,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        paciente: paciente('meu marido', 44, { pronome: 'ele', jaToma: ['varfarina'] }),
        request: pedidoSintoma('dor muscular', 'É pro meu marido, ele torceu o ombro na obra.', [
          'ibuprofeno',
          'diclofenaco',
          'dipirona',
        ], { criterio: 'dor musculoesquelética aguda pede anti-inflamatório ou analgésico, conforme as restrições dele' }),
      },
      {
        id: 'c9',
        arrivalMs: sec(168),
        patienceMaxMs: sec(72),
        nome: 'Genivaldo',
        idade: 55,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('micose', 'Tá coçando e descamando entre os dedos do pé.', ['clotrimazol'], { criterio: 'micose interdigital pede antifúngico tópico em creme (clotrimazol)' }),
      },
    ],
  },
]
