// Turnos jogáveis — fonte da verdade, escrita à mão (não gerada).
//
// Diferente do catálogo de produtos, os turnos carregam intenção pedagógica
// específica e nomeada ("este turno ensina interação medicamentosa"). Gerar o
// cronograma de chegadas/paciência proceduralmente diluiria essa intenção sem
// ganho real nessa escala (8-10 turnos). Todo o rigor de "isso funciona mesmo"
// fica em src/game/shiftValidator.js + scripts/validateShifts.mjs, rodado com
// `npm run validate` sempre que este arquivo muda.
//
// estoque[].id é único dentro de cada turno (não precisa ser global).
// arrivals[].request.type: 'produto' | 'sintoma' | 'receita'.

import { PRODUCTS } from './products.js'

const sec = (n) => n * 1000

function estoqueDeCategorias(categorias, extras = []) {
  const base = PRODUCTS.filter((p) => categorias.includes(p.categoria)).map((p) => ({
    id: p.id,
    produtoId: p.id,
    validadeStatus: 'ok',
  }))
  return [...base, ...extras]
}

function pedidoProduto(produtoId, rotulo, mensagem) {
  return { type: 'produto', produtoId, rotulo, mensagem }
}

function pedidoSintoma(rotulo, mensagem, principiosAceitos) {
  return { type: 'sintoma', rotulo, mensagem, principiosAceitos }
}

function pedidoReceita(rotulo, mensagem, itens) {
  return { type: 'receita', rotulo, mensagem, itens }
}

export const SHIFTS = [
  // ------------------------------------------------------------------------
  {
    id: 'turno-01',
    nome: 'Primeiro Plantão',
    dificuldade: 'fácil',
    resumo: 'Pedidos diretos, um cliente por vez. Só leia o nome certo na prateleira.',
    durationMs: sec(100),
    reputationStart: 60,
    reputationTarget: 68,
    maxQueueVisible: 2,
    unlockedCategories: ['analgesicos'],
    ruleFocus: ['wrongProduct'],
    estoque: estoqueDeCategorias(['analgesicos']),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(70),
        nome: 'Marcos',
        idade: 34,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('doralgin-500', 'Dipirona Sódica 500mg', 'Oi, preciso de Dipirona Sódica 500mg.'),
      },
      {
        id: 'c2',
        arrivalMs: sec(28),
        patienceMaxMs: sec(70),
        nome: 'Beatriz',
        idade: 41,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('tempranol-750', 'Paracetamol 750mg', 'Vim buscar Paracetamol 750mg.'),
      },
      {
        id: 'c3',
        arrivalMs: sec(58),
        patienceMaxMs: sec(65),
        nome: 'Carla',
        idade: 27,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'doralgin-generico-500',
          'Dipirona Sódica 500mg (Genérico)',
          'Tem Dipirona genérico, 500mg?',
        ),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-02',
    nome: 'Turno Tranquilo',
    dificuldade: 'fácil',
    resumo: 'Os clientes agora descrevem o sintoma em vez de pedir o produto pelo nome.',
    durationMs: sec(105),
    reputationStart: 60,
    reputationTarget: 68,
    maxQueueVisible: 2,
    unlockedCategories: ['analgesicos', 'antialergicos', 'gastrointestinal'],
    ruleFocus: ['wrongProduct'],
    estoque: estoqueDeCategorias(['analgesicos', 'antialergicos', 'gastrointestinal']),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(60),
        nome: 'Renato',
        idade: 30,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma(
          'dor de cabeça',
          'Estou com uma dor de cabeça forte, o que vocês têm?',
          ['dipirona', 'paracetamol'],
        ),
      },
      {
        id: 'c2',
        arrivalMs: sec(26),
        patienceMaxMs: sec(58),
        nome: 'Sofia',
        idade: 24,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Estou espirrando muito e com coceira nos olhos.', ['loratadina']),
      },
      {
        id: 'c3',
        arrivalMs: sec(52),
        patienceMaxMs: sec(58),
        nome: 'Diego',
        idade: 45,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('azia', 'Comi demais e estou com uma azia terrível.', ['omeprazol']),
      },
      {
        id: 'c4',
        arrivalMs: sec(78),
        patienceMaxMs: sec(55),
        nome: 'Paula',
        idade: 38,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('febre', 'Estou com febre desde ontem.', ['paracetamol', 'dipirona']),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-03',
    nome: 'Fila Dupla',
    dificuldade: 'fácil-médio',
    resumo: 'Até dois clientes esperando ao mesmo tempo. Alguns precisam de receita.',
    durationMs: sec(115),
    reputationStart: 60,
    reputationTarget: 70,
    maxQueueVisible: 3,
    unlockedCategories: ['analgesicos', 'antialergicos', 'gastrointestinal', 'antibioticos'],
    ruleFocus: ['requiresPrescription'],
    estoque: estoqueDeCategorias(['analgesicos', 'antialergicos', 'gastrointestinal', 'antibioticos']),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(55),
        nome: 'Júlia',
        idade: 29,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('bacterol-500', 'Amoxicilina 500mg', 'Vim buscar meu Amoxicilina 500mg, aqui está a receita.'),
      },
      {
        id: 'c2',
        arrivalMs: sec(16),
        patienceMaxMs: sec(50),
        nome: 'Eduardo',
        idade: 52,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'bacterol-500',
          'Amoxicilina 500mg',
          'Preciso de Amoxicilina 500mg, mas esqueci a receita em casa.',
        ),
      },
      {
        id: 'c3',
        arrivalMs: sec(42),
        patienceMaxMs: sec(55),
        nome: 'Larissa',
        idade: 33,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor de cabeça', 'Dor de cabeça de novo, pode me indicar algo?', ['dipirona', 'paracetamol']),
      },
      {
        id: 'c4',
        arrivalMs: sec(68),
        patienceMaxMs: sec(52),
        nome: 'Otávio',
        idade: 61,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('bacterol-suspensao', 'Amoxicilina Suspensão Infantil', 'Trouxe a receita do meu neto para a Amoxicilina suspensão.'),
      },
      {
        id: 'c5',
        arrivalMs: sec(90),
        patienceMaxMs: sec(50),
        nome: 'Nina',
        idade: 22,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('azia', 'Minha barriga está horrível, o que vocês recomendam?', ['omeprazol']),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-04',
    nome: 'Nomes Parecidos',
    dificuldade: 'médio',
    resumo: 'Genérico, referência e dosagens vizinhas — leia o pedido com atenção.',
    durationMs: sec(115),
    reputationStart: 60,
    reputationTarget: 72,
    maxQueueVisible: 3,
    unlockedCategories: ['analgesicos', 'antialergicos', 'gastrointestinal', 'antibioticos'],
    ruleFocus: ['wrongProduct'],
    estoque: estoqueDeCategorias(['analgesicos', 'antialergicos', 'gastrointestinal', 'antibioticos']),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(48),
        nome: 'Fábio',
        idade: 40,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('doralgin-forte-750', 'Dipirona Sódica 750mg', 'Dipirona 750mg, por favor — não a de 500mg.'),
      },
      {
        id: 'c2',
        arrivalMs: sec(20),
        patienceMaxMs: sec(46),
        nome: 'Helena',
        idade: 31,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'doralgin-generico-500',
          'Dipirona Sódica 500mg (Genérico)',
          'Quero o genérico da Dipirona, não a referência. 500mg.',
        ),
      },
      {
        id: 'c3',
        arrivalMs: sec(42),
        patienceMaxMs: sec(46),
        nome: 'Igor',
        idade: 8,
        humor: 'neutro',
        tags: ['menor_de_12'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto(
          'tempranol-infantil',
          'Paracetamol Infantil (gotas)',
          'É para o meu filho de 8 anos, Paracetamol Infantil.',
        ),
      },
      {
        id: 'c4',
        arrivalMs: sec(66),
        patienceMaxMs: sec(44),
        nome: 'Vanessa',
        idade: 26,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('alergitin-10', 'Loratadina 10mg', 'Loratadina, o comprimido de 10mg.'),
      },
      {
        id: 'c5',
        arrivalMs: sec(88),
        patienceMaxMs: sec(42),
        nome: 'Rodrigo',
        idade: 35,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('doralgin-500', 'Dipirona Sódica 500mg', 'Dipirona Sódica 500mg, o de sempre.'),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-05',
    nome: 'Gestante na Fila',
    dificuldade: 'médio',
    resumo: 'Primeiras contraindicações: gravidez e idade mínima entram em jogo.',
    durationMs: sec(120),
    reputationStart: 60,
    reputationTarget: 74,
    maxQueueVisible: 4,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'gastrointestinal',
      'antibioticos',
      'antigripais',
      'dermatologicos',
    ],
    ruleFocus: ['contraindication'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'gastrointestinal',
      'antibioticos',
      'antigripais',
      'dermatologicos',
    ]),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(48),
        nome: 'Camila',
        idade: 29,
        humor: 'neutro',
        tags: ['gravidez'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma(
          'dor nas costas',
          'Estou grávida de 6 meses e minhas costas estão doendo muito.',
          ['ibuprofeno', 'dipirona'],
        ),
      },
      {
        id: 'c2',
        arrivalMs: sec(20),
        patienceMaxMs: sec(46),
        nome: 'Thiago',
        idade: 58,
        humor: 'neutro',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('doralgin-500', 'Dipirona Sódica 500mg', 'Dipirona Sódica 500mg, aquele de sempre.'),
      },
      {
        id: 'c3',
        arrivalMs: sec(42),
        patienceMaxMs: sec(44),
        nome: 'Lívia',
        idade: 9,
        humor: 'neutro',
        tags: ['menor_de_12'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Minha filha de 9 anos está com coceira e espirrando.', ['loratadina']),
      },
      {
        id: 'c4',
        arrivalMs: sec(64),
        patienceMaxMs: sec(44),
        nome: 'Patrícia',
        idade: 34,
        humor: 'neutro',
        tags: ['gravidez'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('cólica', 'Estou grávida e com uma cólica incômoda.', ['hioscina']),
      },
      {
        id: 'c5',
        arrivalMs: sec(86),
        patienceMaxMs: sec(42),
        nome: 'André',
        idade: 47,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('resfriado', 'Nariz entupido, corpo cortado, resfriado feio.', ['fenilefrina']),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-06',
    nome: 'Estoque Vencido',
    dificuldade: 'médio-avançado',
    resumo: 'Alguns lotes na prateleira estão vencidos — confira a validade antes de entregar.',
    durationMs: sec(120),
    reputationStart: 60,
    reputationTarget: 75,
    maxQueueVisible: 4,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'gastrointestinal',
      'antibioticos',
      'antigripais',
      'dermatologicos',
    ],
    ruleFocus: ['expiredProduct'],
    estoque: [
      ...estoqueDeCategorias([
        'analgesicos',
        'antialergicos',
        'gastrointestinal',
        'antibioticos',
        'antigripais',
        'dermatologicos',
      ]).filter((item) => !['doralgin-500', 'alergitin-10', 'gastrilan-20'].includes(item.produtoId)),
      { id: 'doralgin-500-lote-a', produtoId: 'doralgin-500', validadeStatus: 'ok' },
      { id: 'doralgin-500-lote-b', produtoId: 'doralgin-500', validadeStatus: 'vencido' },
      { id: 'alergitin-10-lote-a', produtoId: 'alergitin-10', validadeStatus: 'vencido' },
      { id: 'alergitin-10-lote-b', produtoId: 'alergitin-10', validadeStatus: 'ok' },
      { id: 'gastrilan-20-lote-a', produtoId: 'gastrilan-20', validadeStatus: 'ok' },
      { id: 'gastrilan-20-lote-b', produtoId: 'gastrilan-20', validadeStatus: 'vencido' },
    ],
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(42),
        nome: 'Vitor',
        idade: 36,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('doralgin-500', 'Dipirona Sódica 500mg', 'Dipirona Sódica 500mg, por favor.'),
      },
      {
        id: 'c2',
        arrivalMs: sec(18),
        patienceMaxMs: sec(40),
        nome: 'Simone',
        idade: 40,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Estou espirrando sem parar, tem algo pra alergia?', ['loratadina']),
      },
      {
        id: 'c3',
        arrivalMs: sec(38),
        patienceMaxMs: sec(40),
        nome: 'Bruno',
        idade: 50,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('azia', 'Azia forte depois do almoço, o que vocês têm?', ['omeprazol']),
      },
      {
        id: 'c4',
        arrivalMs: sec(60),
        patienceMaxMs: sec(38),
        nome: 'Denise',
        idade: 44,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('doralgin-500', 'Dipirona Sódica 500mg', 'Dipirona Sódica 500mg de novo, por favor.'),
      },
      {
        id: 'c5',
        arrivalMs: sec(82),
        patienceMaxMs: sec(38),
        nome: 'Gustavo',
        idade: 28,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('resfriado', 'Nariz entupido e dor no corpo, um resfriado daqueles.', ['fenilefrina']),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-07',
    nome: 'Já Estou Tomando',
    dificuldade: 'avançado',
    resumo: 'Interações medicamentosas: preste atenção no que o cliente já toma.',
    durationMs: sec(125),
    reputationStart: 60,
    reputationTarget: 76,
    maxQueueVisible: 4,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'gastrointestinal',
      'antibioticos',
      'antigripais',
      'dermatologicos',
      'controlados',
    ],
    ruleFocus: ['drugInteraction'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'gastrointestinal',
      'antibioticos',
      'antigripais',
      'dermatologicos',
      'controlados',
    ]),
    distractions: [],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(38),
        nome: 'Roberta',
        idade: 55,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: ['diazepam'],
        request: pedidoSintoma(
          'alergia',
          'Estou tomando um calmante à noite e agora fiquei com alergia, coceira e espirros.',
          ['loratadina', 'dexclorfeniramina'],
        ),
      },
      {
        id: 'c2',
        arrivalMs: sec(20),
        patienceMaxMs: sec(36),
        nome: 'Cláudio',
        idade: 62,
        humor: 'neutro',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('resfriado', 'Resfriado feio, nariz entupido.', ['fenilefrina']),
      },
      {
        id: 'c3',
        arrivalMs: sec(40),
        patienceMaxMs: sec(36),
        nome: 'Fernanda',
        idade: 39,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: ['fenilefrina'],
        request: pedidoProduto(
          'calmapan-5',
          'Diazepam 5mg',
          'Já tomei um antigripal hoje de manhã e agora preciso do meu Diazepam 5mg, aqui está a receita.',
        ),
      },
      {
        id: 'c4',
        arrivalMs: sec(64),
        patienceMaxMs: sec(34),
        nome: 'Wesley',
        idade: 31,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor de cabeça', 'Dor de cabeça forte, o que vocês recomendam?', ['dipirona', 'paracetamol']),
      },
      {
        id: 'c5',
        arrivalMs: sec(88),
        patienceMaxMs: sec(34),
        nome: 'Priscila',
        idade: 45,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: ['dexclorfeniramina'],
        request: pedidoSintoma('resfriado à noite', 'Já tomo um antialérgico à noite e estou resfriada, preciso de algo para dormir melhor.', ['fenilefrina']),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-08',
    nome: 'Retenção Obrigatória',
    dificuldade: 'avançado',
    resumo: 'Produtos controlados exigem reter a receita. Primeira combinação de regras — e o telefone toca.',
    durationMs: sec(130),
    reputationStart: 60,
    reputationTarget: 78,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'gastrointestinal',
      'antibioticos',
      'antigripais',
      'dermatologicos',
      'controlados',
    ],
    ruleFocus: ['controlledWithoutRetention'],
    estoque: estoqueDeCategorias([
      'analgesicos',
      'antialergicos',
      'gastrointestinal',
      'antibioticos',
      'antigripais',
      'dermatologicos',
      'controlados',
    ]),
    distractions: [{ id: 'd1', triggerMs: sec(45), tipo: 'telefone', durationMs: sec(14) }],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(36),
        nome: 'Marcelo',
        idade: 48,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('dorcodin-30', 'Codeína 30mg', 'Vim buscar meu Codeína 30mg, aqui está a receita.'),
      },
      {
        id: 'c2',
        arrivalMs: sec(20),
        patienceMaxMs: sec(34),
        nome: 'Elaine',
        idade: 37,
        humor: 'neutro',
        tags: ['gravidez'],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('calmapan-5', 'Diazepam 5mg', 'Preciso do meu Diazepam 5mg, tenho a receita aqui.'),
      },
      {
        id: 'c3',
        arrivalMs: sec(42),
        patienceMaxMs: sec(34),
        nome: 'Ricardo',
        idade: 29,
        humor: 'estressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor de cabeça', 'Dor de cabeça horrível, me ajuda logo?', ['dipirona', 'paracetamol']),
      },
      {
        id: 'c4',
        arrivalMs: sec(66),
        patienceMaxMs: sec(32),
        nome: 'Tânia',
        idade: 60,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('dorcodin-30', 'Codeína 30mg', 'Codeína 30mg de novo esse mês, aqui está a receita.'),
      },
      {
        id: 'c5',
        arrivalMs: sec(90),
        patienceMaxMs: sec(32),
        nome: 'Felipe',
        idade: 33,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('azia', 'Azia terrível, o que vocês têm?', ['omeprazol']),
      },
      {
        id: 'c6',
        arrivalMs: sec(108),
        patienceMaxMs: sec(30),
        nome: 'Aline',
        idade: 26,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Estou espirrando muito, tem algo pra alergia?', ['loratadina']),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-09',
    nome: 'Hora do Rush',
    dificuldade: 'expert',
    resumo: 'Todas as categorias liberadas, fila cheia e duas distrações no meio do turno.',
    durationMs: sec(140),
    reputationStart: 60,
    reputationTarget: 80,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'gastrointestinal',
      'antibioticos',
      'antigripais',
      'dermatologicos',
      'controlados',
    ],
    ruleFocus: ['contraindication', 'drugInteraction', 'controlledWithoutRetention'],
    estoque: [
      ...estoqueDeCategorias([
        'analgesicos',
        'antialergicos',
        'gastrointestinal',
        'antibioticos',
        'antigripais',
        'dermatologicos',
        'controlados',
      ]).filter((item) => item.produtoId !== 'doralgin-500'),
      { id: 'doralgin-500-lote-a', produtoId: 'doralgin-500', validadeStatus: 'ok' },
      { id: 'doralgin-500-lote-b', produtoId: 'doralgin-500', validadeStatus: 'vencido' },
    ],
    distractions: [
      { id: 'd1', triggerMs: sec(35), tipo: 'telefone', durationMs: sec(12) },
      {
        id: 'd2',
        triggerMs: sec(95),
        tipo: 'troco',
        durationMs: sec(14),
        options: [
          { id: 'a', label: 'R$ 3,50' },
          { id: 'b', label: 'R$ 8,00' },
          { id: 'c', label: 'R$ 13,50' },
        ],
        correctChoiceId: 'c',
      },
    ],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(32),
        nome: 'Douglas',
        idade: 40,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('doralgin-500', 'Dipirona Sódica 500mg', 'Dipirona Sódica 500mg, rápido por favor.'),
      },
      {
        id: 'c2',
        arrivalMs: sec(16),
        patienceMaxMs: sec(30),
        nome: 'Michele',
        idade: 31,
        humor: 'neutro',
        tags: ['gravidez'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor nas costas', 'Grávida de 7 meses, as costas estão me matando.', ['ibuprofeno', 'dipirona']),
      },
      {
        id: 'c3',
        arrivalMs: sec(34),
        patienceMaxMs: sec(30),
        nome: 'Anderson',
        idade: 50,
        humor: 'estressado',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('dorcodin-30', 'Codeína 30mg', 'Codeína 30mg com receita, e rápido, a fila está grande.'),
      },
      {
        id: 'c4',
        arrivalMs: sec(52),
        patienceMaxMs: sec(28),
        nome: 'Juliana',
        idade: 44,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: ['dexclorfeniramina'],
        request: pedidoProduto('calmapan-5', 'Diazepam 5mg', 'Já tomo um antialérgico à noite, mas preciso do Diazepam 5mg, receita aqui.'),
      },
      {
        id: 'c5',
        arrivalMs: sec(70),
        patienceMaxMs: sec(28),
        nome: 'Kelly',
        idade: 7,
        humor: 'neutro',
        tags: ['menor_de_12'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('febre', 'Minha filha de 7 anos está com febre.', ['paracetamol', 'dipirona']),
      },
      {
        id: 'c6',
        arrivalMs: sec(88),
        patienceMaxMs: sec(26),
        nome: 'Vagner',
        idade: 55,
        humor: 'neutro',
        tags: ['hipertensao'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('resfriado', 'Resfriado forte, nariz entupido.', ['fenilefrina']),
      },
      {
        id: 'c7',
        arrivalMs: sec(106),
        patienceMaxMs: sec(26),
        nome: 'Bianca',
        idade: 25,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Coceira e espirros sem parar.', ['loratadina']),
      },
    ],
  },

  // ------------------------------------------------------------------------
  {
    id: 'turno-10',
    nome: 'Fechamento Perfeito',
    dificuldade: 'expert/mestre',
    resumo: 'Turno de prova: todas as regras em jogo, fila cheia, paciência curta, duas distrações.',
    durationMs: sec(145),
    reputationStart: 60,
    reputationTarget: 84,
    maxQueueVisible: 5,
    unlockedCategories: [
      'analgesicos',
      'antialergicos',
      'gastrointestinal',
      'antibioticos',
      'antigripais',
      'dermatologicos',
      'controlados',
    ],
    ruleFocus: [
      'requiresPrescription',
      'controlledWithoutRetention',
      'contraindication',
      'drugInteraction',
      'expiredProduct',
      'wrongProduct',
    ],
    estoque: [
      ...estoqueDeCategorias([
        'analgesicos',
        'antialergicos',
        'gastrointestinal',
        'antibioticos',
        'antigripais',
        'dermatologicos',
        'controlados',
      ]).filter((item) => !['alergitin-10', 'bacterol-500'].includes(item.produtoId)),
      { id: 'alergitin-10-lote-a', produtoId: 'alergitin-10', validadeStatus: 'ok' },
      { id: 'alergitin-10-lote-b', produtoId: 'alergitin-10', validadeStatus: 'vencido' },
      { id: 'bacterol-500-lote-a', produtoId: 'bacterol-500', validadeStatus: 'ok' },
      { id: 'bacterol-500-lote-b', produtoId: 'bacterol-500', validadeStatus: 'vencido' },
    ],
    distractions: [
      { id: 'd1', triggerMs: sec(30), tipo: 'telefone', durationMs: sec(12) },
      {
        id: 'd2',
        triggerMs: sec(75),
        tipo: 'troco',
        durationMs: sec(12),
        options: [
          { id: 'a', label: 'R$ 6,50' },
          { id: 'b', label: 'R$ 11,00' },
          { id: 'c', label: 'R$ 21,00' },
        ],
        correctChoiceId: 'b',
      },
      { id: 'd3', triggerMs: sec(115), tipo: 'telefone', durationMs: sec(10) },
    ],
    arrivals: [
      {
        id: 'c1',
        arrivalMs: sec(0),
        patienceMaxMs: sec(28),
        nome: 'Sandra',
        idade: 30,
        humor: 'estressado',
        tags: ['gravidez'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('dor nas costas', 'Grávida e com dor nas costas, o que posso tomar?', ['ibuprofeno', 'dipirona']),
      },
      {
        id: 'c2',
        arrivalMs: sec(14),
        patienceMaxMs: sec(26),
        nome: 'Henrique',
        idade: 44,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoReceita(
          'receita de 2 itens',
          'Aqui está minha receita: Amoxicilina 500mg e Omeprazol 20mg.',
          [
            { principioAtivo: 'amoxicilina', rotulo: 'Amoxicilina 500mg' },
            { principioAtivo: 'omeprazol', rotulo: 'Omeprazol 20mg' },
          ],
        ),
      },
      {
        id: 'c3',
        arrivalMs: sec(30),
        patienceMaxMs: sec(26),
        nome: 'Gabriela',
        idade: 9,
        humor: 'neutro',
        tags: ['menor_de_12'],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Minha filha de 9 anos, coceira e espirros.', ['loratadina']),
      },
      {
        id: 'c4',
        arrivalMs: sec(48),
        patienceMaxMs: sec(24),
        nome: 'Márcio',
        idade: 63,
        humor: 'estressado',
        tags: ['hipertensao'],
        hasReceita: true,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('calmapan-5', 'Diazepam 5mg', 'Meu Diazepam 5mg, com receita, rápido por favor.'),
      },
      {
        id: 'c5',
        arrivalMs: sec(66),
        patienceMaxMs: sec(24),
        nome: 'Adriana',
        idade: 52,
        humor: 'neutro',
        tags: [],
        hasReceita: true,
        jaTomaPrincipiosAtivos: ['dexclorfeniramina'],
        request: pedidoProduto('calmapan-5', 'Diazepam 5mg', 'Já tomo antialérgico à noite, mas preciso do Diazepam 5mg — receita aqui.'),
      },
      {
        id: 'c6',
        arrivalMs: sec(84),
        patienceMaxMs: sec(22),
        nome: 'Leandro',
        idade: 38,
        humor: 'apressado',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('bacterol-500', 'Amoxicilina 500mg', 'Amoxicilina 500mg, sem receita mesmo, tenta aí.'),
      },
      {
        id: 'c7',
        arrivalMs: sec(102),
        patienceMaxMs: sec(22),
        nome: 'Cristiane',
        idade: 41,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoSintoma('alergia', 'Coceira, espirros, o que vocês recomendam?', ['loratadina']),
      },
      {
        id: 'c8',
        arrivalMs: sec(120),
        patienceMaxMs: sec(20),
        nome: 'Pedro',
        idade: 47,
        humor: 'neutro',
        tags: [],
        hasReceita: false,
        jaTomaPrincipiosAtivos: [],
        request: pedidoProduto('doralgin-500', 'Dipirona Sódica 500mg', 'Dipirona Sódica 500mg, para fechar o dia.'),
      },
    ],
  },
]

export function getShiftById(id) {
  return SHIFTS.find((s) => s.id === id) ?? null
}
